const photoCollection = [
  {
    id: 1,
    title: "Cast and Crew",
    url: "img/PatrickJerry_Web.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 2,
    title: "Cast and Crew 2",
    url: "img/TimMargret_Web.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 3,
    title: "Cast and Crew 3",
    url: "img/FullGroup_Web.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 4,
    title: "Vestibule",
    url: "img/Vestibule_1_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 5,
    title: "Lawn & Stairs",
    url: "img/LawnStairs_1_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 6,
    title: "Greenhouse 3",
    url: "img/Greenhouse3_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 7,
    title: "Greenhouse 2",
    url: "img/Greenhouse02_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 8,
    title: "Fallen Tree",
    url: "img/FallenTree.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 9,
    title: "City 2",
    url: "img/City2_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 10,
    title: "Bikes",
    url: "img/bikes_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 11,
    title: "3 Buildings",
    url: "img/3Bldgs_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 12,
    title: "Two Arches",
    url: "img/2Arches_1_WebTag_1500.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 13,
    title: "Ajsean 1",
    url: "img/Ajsean_Fin01.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 14,
    title: "Ajsean 2",
    url: "img/Ajsean_Fin02.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 15,
    title: "Christian 1",
    url: "img/christian01_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 16,
    title: "Christian 2",
    url: "img/Christian02_W.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 17,
    title: "Emily 1",
    url: "img/Emily_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 18,
    title: "Emily 2",
    url: "img/Emily02_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 19,
    title: "Federico 1",
    url: "img/Federico_W_01.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 20,
    title: "Federico 2",
    url: "img/Federico_Fin_02.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 21,
    title: "Lottie",
    url: "img/Lottie_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 22,
    title: "Matheus",
    url: "img/Matheus_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 23,
    title: "Melody 1",
    url: "img/Melody01_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 24,
    title: "Melody 2",
    url: "img/Melody02_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 25,
    title: "Monica 1",
    url: "img/Monica_W.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 26,
    title: "Monica 2",
    url: "img/Monica2_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 27,
    title: "Sean 1",
    url: "img/Sean_01_Fin.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 28,
    title: "Sean 2",
    url: "img/Sean_02_Fin-2.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 29,
    title: "Sean W",
    url: "img/Sean_W_01.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 30,
    title: "Sean W",
    url: "img/Sean_W_02.jpg",
    category: ["digital", "color", "portrait", "cinematic"],
    description: "This is the description.",
  },
  {
    id: 31,
    title: "Achmed",
    url: "img/Achmed.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 32,
    title: "Brennan",
    url: "img/Brennan.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 33,
    title: "Chris Holmes",
    url: "img/ChrisHolmes.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 34,
    title: "Chris Holmes 2",
    url: "img/ChrisHolmes02.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 35,
    title: "Dave The Producer",
    url: "img/DaveTheProducer.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 36,
    title: "Devand",
    url: "img/Devand.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 37,
    title: "Dyanis",
    url: "img/Dyanis.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 38,
    title: "Harry",
    url: "img/HarryPortrait_Web.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 39,
    title: "Isabel",
    url: "img/Isabel.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 40,
    title: "Jackie",
    url: "img/Jackie.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 41,
    title: "Jaeno",
    url: "img/Jaeno.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 42,
    title: "Kim",
    url: "img/Kim.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 43,
    title: "Korveil",
    url: "img/Korveil.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 44,
    title: "Lindsay",
    url: "img/Lindsay.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 45,
    title: "Meghan",
    url: "img/Meghan.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 46,
    title: "Michelle",
    url: "img/Michelle.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 47,
    title: "Montse",
    url: "img/Montse.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 48,
    title: "Montse 2",
    url: "img/Montse2.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 49,
    title: "Mychal",
    url: "img/Mychal.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 50,
    title: "Pamela",
    url: "img/Pamela.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 51,
    title: "Patrick M",
    url: "img/PatrickMarlett.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 52,
    title: "PHI Team",
    url: "img/PHI_Training.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 53,
    title: "Pla",
    url: "img/Pla2.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 54,
    title: "Plastic Boots",
    url: "img/PlasticBoots.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 55,
    title: "Tanya",
    url: "img/Tanya.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 56,
    title: "Tati",
    url: "img/Tati.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 57,
    title: "Tyra",
    url: "img/Tyra.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 58,
    title: "Yuri",
    url: "img/Yuri.jpg",
    category: ["digital", "color", "portrait"],
    description: "This is the description.",
  },
  {
    id: 60,
    title: "Gianni",
    url: "img/Gianni02_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 61,
    title: "Mark",
    url: "img/MarkA_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 62,
    title: "Mentors & Peers",
    url: "img/MentorAndPeers_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 63,
    title: "MentorsGroup",
    url: "img/MentorsGroup_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 64,
    title: "Monica & Gianni",
    url: "img/MonicaGianni_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 65,
    title: "Neko & Danasia",
    url: "img/NekoDanasia_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 66,
    title: "Plyne Christian & Kevin",
    url: "img/PlyneChristianKevin_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 67,
    title: "Rosemary",
    url: "img/Rosemary_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 68,
    title: "Tiffany",
    url: "img/Tiffany_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 69,
    title: "Curved Path",
    url: "img/CurvedPath01_W.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 70,
    title: "Night Shot",
    url: "img/NightShot02_IMA_Fin.jpg",
    category: ["film", "b&w", "portrait", "4x5"],
    description: "This is the description.",
  },
  {
    id: 71,
    title: "Pink Stairs",
    url: "img/PinkFlowers2_Fin.jpg",
    category: ["film", "color", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 72,
    title: "Ramp",
    url: "img/RampBldg_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 73,
    title: "Rusty Wall at Sunset",
    url: "img/RustyWall01_Fin.jpg",
    category: ["film", "color", "landscape", "4x5"],
    description: "This is the description.",
  },

];

export default photoCollection