const BASE = process.env.PUBLIC_URL;

const photoCollection = [
  {
    id: 1,
    title: "Cast and Crew",
    full: `${BASE}/img/Env_FullGroup_Web.avif`,
    thumb: `${BASE}/img/thumb/Env_FullGroup_Web.avif`,
    category: ["digital", "color", "environmental"],
    description: "The cast and crew from from Patrick's film projects",
    alt: "Six people sitting and standing around a couch.",
  },
  {
    id: 2,
    title: "Pamela",
    full: `${BASE}/img/Env_Pamela.avif`,
    thumb: `${BASE}/img/thumb/Env_Pamela.avif`,
    category: ["digital", "color", "environmental"],
    description: "Pamela portrait.",
    alt: "Young woman wearing flowers in her hair in front of a wall of photos.",
  },
  {
    id: 3,
    title: "Harry's Farm",
    full: `${BASE}/img/Env_HarryPortrait_Web.jpg`,
    thumb: `${BASE}/img/thumb/Env_HarryPortrait_Web.avif`,
    category: ["digital", "color", "environmental"],
    description: "Farmer Harry's portrait",
    alt: "Farmer stands cross armed in front of tractor",
  },
  {
    id: 4,
    title: "Pla",
    full: `${BASE}/img/Env_Pla2.avif`,
    thumb: `${BASE}/img/thumb/Env_Pla2.avif`,
    category: ["digital", "color", "environmental"],
    description: "Pla portrait.",
    alt: "Woman sitting in a skeletal boat sculpture",
  },
  {
    id: 5,
    title: "Montse I",
    full: `${BASE}/img/Env_Montse.avif`,
    thumb: `${BASE}/img/thumb/Env_Montse.avif`,
    category: ["digital", "color", "environmental"],
    description: "Montse portrait.",
    alt: "Woman sitting on couch in front of bookshelf",
  },
  {
    id: 6,
    title: "Montse II",
    full: `${BASE}/img/Env_Montse2.avif`,
    thumb: `${BASE}/img/thumb/Env_Montse2.avif`,
    category: ["digital", "color", "environmental"],
    description: "Montse portrait two.",
    alt: "Woman standing in art gallery.",
  },
  {
    id: 7,
    title: "Obi Soulstar",
    full: `${BASE}/img/Mus_Obi_Blur_Fin_700tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Obi_Blur_Fin_700tag.avif`,
    category: ["digital", "color", "music"],
    description: "Obi Soulstar portrait",
    alt: "Man with sunglasses making blurry movements",
  },
  {
    id: 8,
    title: "The Sometimes Family",
    full: `${BASE}/img/Mus_STFamily_1.avif`,
    thumb: `${BASE}/img/thumb/Mus_STFamily_1.avif`,
    category: ["digital", "color", "music"],
    description: "The Sometimes Family portrait",
    alt: "Group of musicians under a canopy.",
  },
  {
    id: 9,
    title: "Maris",
    full: `${BASE}/img/Crump_Maris-port_0083_WebTag.avif`,
    thumb: `${BASE}/img/thumb/Crump_Maris-port_0083_WebTag.avif`,
    category: ["film", "b&w", "studio"],
    description: "Maris portrait",
    alt: "Tattooed woman in front of crinkled black backdrop.",
  },
  {
    id: 10,
    title: "Mentor's Group",
    full: `${BASE}/img/LF_MentorsGroup_Fin.jpg`,
    thumb: `${BASE}/img/thumb/LF_MentorsGroup_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Mentor's group portrait",
    alt: "Group photo broken up over several 4x5 film frames",
  },
  {
    id: 11,
    title: "Selina II",
    full: `${BASE}/img/Mus_Selina_0134_700tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Selina_0134_700tag.avif`,
    category: ["digital", "color", "music"],
    description: "Selina portrait two",
    alt: "Hippy woman with guitar, backlit by sunlight, and lens flare",
  },
  {
    id: 12,
    title: "Brennan",
    full: `${BASE}/img/Env_Brennan.avif`,
    thumb: `${BASE}/img/thumb/Env_Brennan.avif`,
    category: ["digital", "color", "environmental"],
    description: "Brennan portrait",
    alt: "Man standing in NYC's Meat Packing district",
  },
  {
    id: 13,
    title: "Chris I",
    full: `${BASE}/img/Env_ChrisHolmes.jpg`,
    thumb: `${BASE}/img/thumb/Env_ChrisHolmes.avif`,
    category: ["digital", "color", "environmental"],
    description: "Chris Holmes portrait.",
    alt: "Man in collared shirt in front of glass wall.",
  },
  {
    id: 14,
    title: "Chris II",
    full: `${BASE}/img/Env_ChrisHolmes02.jpg`,
    thumb: `${BASE}/img/thumb/Env_ChrisHolmes02.avif`,
    category: ["digital", "color", "environmental"],
    description: "Chris Holmes portrait two.",
    alt: "Headshot of a man in a collared shirt.",
  },
  {
    id: 15,
    title: "Devand",
    full: `${BASE}/img/Env_Devand.jpg`,
    thumb: `${BASE}/img/thumb/Env_Devand.avif`,
    category: ["digital", "color", "environmental"],
    description: "Devand portrait",
    alt: "Man in suit in front of colorful sunset.",
  },
  {
    id: 16,
    title: "Dyanis",
    full: `${BASE}/img/Env_Dyanis.jpg`,
    thumb: `${BASE}/img/thumb/Env_Dyanis.avif`,
    category: ["digital", "color", "environmental"],
    description: "Dyanis portrait",
    alt: "Woman sitting in chair in living room.",
  },
  {
    id: 17,
    title: "Cast and Crew II",
    full: `${BASE}/img/Env_PatrickJerry_Web.jpg`,
    thumb: `${BASE}/img/thumb/Env_PatrickJerry_Web.avif`,
    category: ["digital", "color", "environmental"],
    description: "Patrick and Jerry portrait.",
    alt: "Two professional dressed men sitting at table.",
  },
  {
    id: 18,
    title: "Cast and Crew III",
    full: `${BASE}/img/Env_TimMargret_Web.jpg`,
    thumb: `${BASE}/img/thumb/Env_TimMargret_Web.avif`,
    category: ["digital", "color", "environmental"],
    description: "Tim and Margret portrait",
    alt: "Well dressed woman sitting in chair and man standing behind her.",
  },
  {
    id: 19,
    title: "Isabel",
    full: `${BASE}/img/Env_Isabel.jpg`,
    thumb: `${BASE}/img/thumb/Env_Isabel.avif`,
    category: ["digital", "color", "environmental"],
    description: "Isabel portrait",
    alt: "Woman sitting on couch in living room with art on the wall.",
  },
  {
    id: 20,
    title: "Jackie",
    full: `${BASE}/img/Env_Jackie.avif`,
    thumb: `${BASE}/img/thumb/Env_Jackie.avif`,
    category: ["digital", "color", "environmental"],
    description: "Jackie portrait.",
    alt: "Woman sitting on bed with pictures behind her.",
  },
  {
    id: 26,
    title: "Kim",
    full: `${BASE}/img/Env_Kim.avif`,
    thumb: `${BASE}/img/thumb/Env_Kim.avif`,
    category: ["digital", "color", "environmental"],
    description: "Kim portrait",
    alt: "Woman standing in park.",
  },
  {
    id: 27,
    title: "Lindsay",
    full: `${BASE}/img/Env_Lindsay.avif`,
    thumb: `${BASE}/img/thumb/Env_Lindsay.avif`,
    category: ["digital", "color", "environmental"],
    description: "Lindsay portrait",
    alt: "Woman in 1950's outfit admiring the ferris wheel in Coney Island.",
  },
  {
    id: 28,
    title: "Meghan",
    full: `${BASE}/img/Env_Meghan.avif`,
    thumb: `${BASE}/img/thumb/Env_Meghan.avif`,
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 29,
    title: "Michelle",
    full: `${BASE}/img/Env_Michelle.avif`,
    thumb: `${BASE}/img/thumb/Env_Michelle.avif`,
    category: ["digital", "color", "environmental"],
    description: "Meghan portrait.",
    alt: "Woman standing in front of the Five Points graffiti building in Queens.",
  },
  {
    id: 30,
    title: "Mychal",
    full: `${BASE}/img/Env_Mychal.avif`,
    thumb: `${BASE}/img/thumb/Env_Mychal.avif`,
    category: ["digital", "color", "environmental"],
    description: "Mychal portrait",
    alt: "Woman with sundress sitting in Bryant Park.",
  },
  {
    id: 31,
    title: "Patrick M",
    full: `${BASE}/img/Env_PatrickMarlett.avif`,
    thumb: `${BASE}/img/thumb/Env_PatrickMarlett.avif`,
    category: ["digital", "color", "environmental"],
    description: "Patrick portrait",
    alt: "Man, with crossed arms, standing in a park.",
  },
  {
    id: 32,
    title: "PHI Team",
    full: `${BASE}/img/Env_PHI_Training.avif`,
    thumb: `${BASE}/img/thumb/Env_PHI_Training.avif`,
    category: ["digital", "color", "environmental"],
    description: "PHI Team portrait",
    alt: "Three people sitting in an office in the Bronx.",
  },
  {
    id: 33,
    title: "Tanya",
    full: `${BASE}/img/Env_Tanya.avif`,
    thumb: `${BASE}/img/thumb/Env_Tanya.avif`,
    category: ["digital", "color", "environmental"],
    description: "Tanya portrait.",
    alt: "Woman standing in front of a curbed path in a Brooklyn park.",
  },
  {
    id: 34,
    title: "Tati",
    full: `${BASE}/img/Env_Tati.avif`,
    thumb: `${BASE}/img/thumb/Env_Tati.avif`,
    category: ["digital", "color", "environmental"],
    description: "Tati portrait.",
    alt: "Woman standing in front of a spiky sculpture.",
  },
  {
    id: 35,
    title: "Tyra",
    full: `${BASE}/img/Env_Tyra.avif`,
    thumb: `${BASE}/img/thumb/Env_Tyra.avif`,
    category: ["digital", "color", "environmental"],
    description: "Tyra portrait.",
    alt: "Woman standing on a pier in front of cloudy landscape.",
  },
  {
    id: 36,
    title: "Yuri",
    full: `${BASE}/img/Env_Yuri.avif`,
    thumb: `${BASE}/img/thumb/Env_Yuri.avif`,
    category: ["digital", "color", "environmental"],
    description: "Yuri portrait.",
    alt: "Woman standing in front of skyline of Manhattan.",
  },
  {
    id: 37,
    title: "Gianni",
    full: `${BASE}/img/LF_Gianni02_Fin.jpg`,
    thumb: `${BASE}/img/thumb/LF_Gianni02_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Gianni portrait.",
    alt: "Man standing in front of white backdrop with hand to his face.",
  },
  {
    id: 38,
    title: "Mark",
    full: `${BASE}/img/LF_MarkA_Fin.jpg`,
    thumb: `${BASE}/img/thumb/LF_MarkA_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Mark portrait.",
    alt: "Man with glasses standing in front of white backdrop with hands on neck.",
  },
  {
    id: 39,
    title: "Mentors & Peers",
    full: `${BASE}/img/LF_MentorAndPeers_Fin.avif`,
    thumb: `${BASE}/img/thumb/LF_MentorAndPeers_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Mentors and Peers portrait",
    alt: "Group of four people leaning on each other in front of white backdrop.",
  },
  {
    id: 40,
    title: "Monica & Gianni",
    full: `${BASE}/img/LF_MonicaGianni_Fin.jpg`,
    thumb: `${BASE}/img/thumb/LF_MonicaGianni_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Monica and Gianni portrait",
    alt: "Woman and man standing shoulder to shoulder in front of white backdrop.",
  },
  //

  {
    id: 41,
    title: "Neko & Danasia",
    full: `${BASE}/img/LF_NekoDanasia_Fin.avif`,
    thumb: `${BASE}/img/thumb/LF_NekoDanasia_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Neko and Danasia portrait.",
    alt: "Man standing with his arm around a woman's shoulder in front of a white backdrop.",
  },
  {
    id: 42,
    title: "Plyne, Christian & Kevin",
    full: `${BASE}/img/LF_PlyneChristianKevin_Fin.avif`,
    thumb: `${BASE}/img/thumb/LF_PlyneChristianKevin_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Plyne, Christiand, and Kevin potrait",
    alt: "Three men leaning on each other in front of a white backdrop.",
  },
  {
    id: 43,
    title: "Rosemary",
    full: `${BASE}/img/LF_Rosemary_Fin.jpg`,
    thumb: `${BASE}/img/thumb/LF_Rosemary_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Rosemary portrait.",
    alt: "Woman with her hands crossed in front of her standing in front of white backdrop.",
  },
  {
    id: 44,
    title: "Tiffany",
    full: `${BASE}/img/LF_Tiffany_Fin.jpg`,
    thumb: `${BASE}/img/thumb/LF_Tiffany_Fin.avif`,
    category: ["film", "b&w", "studio", "4x5"],
    description: "Tiffany portrait",
    alt: "Woman flaunting her necklace in front of a white backdrop.",
  },
  {
    id: 45,
    title: "Bikes at Ráðhús Reykjavíkur (Iceland)",
    full: `${BASE}/img/Land_bikes_W.avif`,
    thumb: `${BASE}/img/thumb/Land_bikes_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Bikes in front of Ráðhús Reykjavíkur (Riykjavik City Hall)",
    alt: "Two bikes parked in front of Ráðhús Reykjavíkur (Riykjavik City Hall) at night.",
  },
  {
    id: 46,
    title: "Jacob Wrey Mould Fountain",
    full: `${BASE}/img/Land_Fountain_W.avif`,
    thumb: `${BASE}/img/thumb/Land_Fountain_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Jacob Wrey Mould Fountain",
    alt: "Jacob Wrey Mould Fountain at night.",
  },
  {
    id: 47,
    title: "Kennedy to Koch Bridge",
    full: `${BASE}/img/Land_BridgeView_Fin3.avif`,
    thumb: `${BASE}/img/thumb/Land_BridgeView_Fin3.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Kennedy and Koch bridge in Astoria.",
    alt: "Kennedy bridge in foreground and Koch bridge arch in background.",
  },
  {
    id: 48,
    title: "Pier 15",
    full: `${BASE}/img/Land_Pier01_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_Pier01_Fin.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Pier fifteen at night.",
    alt: "Slatted roof of Pier 15 next to Manhattan skyline at night.",
  },
  {
    id: 49,
    title: "Long Beach",
    full: `${BASE}/img/Land_00204_LB_PacificAve_01_Web.avif`,
    thumb: `${BASE}/img/thumb/Land_00204_LB_PacificAve_01_Web.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Long Beach Condos",
    alt: "Building in perspective at night.",
  },
  {
    id: 50,
    title: "Curved Path",
    full: `${BASE}/img/Land_CurvedPath01_W.avif`,
    thumb: `${BASE}/img/thumb/Land_CurvedPath01_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Curved path on Riverside Drive.",
    alt: "Person descending ramp in black and white",
  },
  {
    id: 51,
    title: "Pier 15 Upper Level",
    full: `${BASE}/img/Land_NightShot02_IMA_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_NightShot02_IMA_Fin.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Pier 15 with lit up stairs and Manhattan skyline.",
    alt: "Lit stairs asscending to a Manhattan skyline",
  },
  {
    id: 52,
    title: "Cloisters",
    full: `${BASE}/img/Land_PinkFlowers2_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_PinkFlowers2_Fin.avif`,
    category: ["film", "color", "landscape", "4x5"],
    description: "Stairs in the Cloisters",
    alt: "Stairs highlighted by fallen pink flower petals.",
  },
  {
    id: 53,
    title: "Sloped Building",
    full: `${BASE}/img/Land_RampBldg_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_RampBldg_Fin.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Manhattan architecture",
    alt: "NYC architecture at night",
  },
  {
    id: 54,
    title: "Rust",
    full: `${BASE}/img/Land_RustyWall01_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_RustyWall01_Fin.avif`,
    category: ["film", "color", "landscape", "4x5"],
    description: "Rusty Wall at Sunset",
    alt: "Rusty Wall at Sunset",
  },
  {
    id: 55,
    title: "Vestibule",
    full: `${BASE}/img/Land_Vestibule_1_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_Vestibule_1_Fin.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Landscape image of vestibule in the Cloisters",
    alt: "Black and white image of a stone vestibule.",
  },
  {
    id: 56,
    title: "Iceland Greenhouse I",
    full: `${BASE}/img/Land_Greenhouse3_W.avif`,
    thumb: `${BASE}/img/thumb/Land_Greenhouse3_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Icelandic Greenhouse",
    alt: "Glowing greenhouse at night",
  },
  {
    id: 57,
    title: "Iceland Greenhouse II",
    full: `${BASE}/img/Land_Greenhouse02_W.avif`,
    thumb: `${BASE}/img/thumb/Land_Greenhouse02_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Icelandic Greenhouse angle II",
    alt: "Glowing greenhouse at night",
  },
  {
    id: 58,
    title: "Fallen Tree",
    full: `${BASE}/img/Land_FallenTree.avif`,
    thumb: `${BASE}/img/thumb/Land_FallenTree.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Fallen tree in the woods",
    alt: "Fallen tree with spikey branches in black and white.",
  },
  {
    id: 59,
    title: "Central Park",
    full: `${BASE}/img/Land_City2_W.avif`,
    thumb: `${BASE}/img/thumb/Land_City2_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Central Park at night",
    alt: "Manhattan skyline from central park in black and white.",
  },
  {
    id: 60,
    title: "Lawn & Stairs",
    full: `${BASE}/img/Land_LawnStairs_1_W.jpg`,
    thumb: `${BASE}/img/thumb/Land_LawnStairs_1_W.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Manhattan park at night",
    alt: "Cloudy sky over stairs, at night.",
  },
  {
    id: 61,
    title: "3 Buildings",
    full: `${BASE}/img/Land_3Bldgs_Fin.avif`,
    thumb: `${BASE}/img/thumb/Land_3Bldgs_Fin.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Manhattan architecture",
    alt: "Close of up three building in the Manhattan skyline.",
  },
  {
    id: 62,
    title: "Two Arches",
    full: `${BASE}/img/Land_2Arches_1_WebTag_1500.avif`,
    thumb: `${BASE}/img/thumb/Land_2Arches_1_WebTag_1500.avif`,
    category: ["film", "b&w", "landscape", "4x5"],
    description: "Two stone arches from the Cloisters",
    alt: "A stone arch from within a stone arch in black and white.",
  },
  {
    id: 63,
    title: "Sean W I",
    full: `${BASE}/img/Cinema_Sean_W_01.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Sean_W_01.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Sean embodying Rebel Without a Cause",
    alt: "Man in 1950's type outfit leaning on a lightpole.",
  },
  {
    id: 64,
    title: "Sean W II",
    full: `${BASE}/img/Cinema_Sean_W_02.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Sean_W_02.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Sean embodying Rebel Without a Cause.",
    alt: "Man in 1950's type outfit under an overpass",
  },
  {
    id: 65,
    title: "Emily I",
    full: `${BASE}/img/Cinema_Emily_Fin.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Emily_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Emily embodying Silence of the Lambs",
    alt: "Woman hiding behind a tree in the woods",
  },
  {
    id: 66,
    title: "Emily II",
    full: `${BASE}/img/Cinema_Emily02_Fin.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Emily02_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Emily embodying Silence of the Lambs",
    alt: "Woman in behind a jail bars",
  },
  {
    id: 67,
    title: "Christian I",
    full: `${BASE}/img/Cinema_Christian01_Fin.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Christian01_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Christian embodying The Shining",
    alt: "Man in a torn t-shirt at the foot of the stairs looking crazed.",
  },
  {
    id: 68,
    title: "Christian II",
    full: `${BASE}/img/Cinema_Christian02_W.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Christian02_W.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Christian embodying The Shining",
    alt: "Man next to a pillar staring up with great intensity.",
  },
  {
    id: 69,
    title: "Ajsean I",
    full: `${BASE}/img/Cinema_Ajsean_Fin01.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Ajsean_Fin01.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Ajsean embodying The Breakfast Club",
    alt: "Woman hiding next to tree holding books and wearing hat",
  },
  {
    id: 70,
    title: "Ajsean II",
    full: `${BASE}/img/Cinema_Ajsean_Fin02.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Ajsean_Fin02.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Ajsean embodying The Breakfast Club",
    alt: "Woman sitting on rock in park while clutching books.",
  },
  {
    id: 71,
    title: "Federico I",
    full: `${BASE}/img/Cinema_Federico_W_01.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Federico_W_01.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Federico embodying The Unbearable Lightness of Being",
    alt: "Man in tree wearing shirt, tie, and vest with suitcoat next to him.",
  },
  {
    id: 72,
    title: "Federico II",
    full: `${BASE}/img/Cinema_Federico_Fin_02.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Federico_Fin_02.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Federico embodying The Unbearable Lightness of Being",
    alt: "Man sitting on a rock in a park looking forelorn.",
  },
  {
    id: 73,
    title: "Lottie",
    full: `${BASE}/img/Env_Lottie_Fin.avif`,
    thumb: `${BASE}/img/thumb/Env_Lottie_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Lottie embodying American Psycho",
    alt: "Woman wearing a suit and tie, crouched below a payphone with blood on her face.",
  },
  {
    id: 74,
    title: "Matheus",
    full: `${BASE}/img/Cinema_Matheus_Fin.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Matheus_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Matheus embodying Rear Window",
    alt: "Man in suit hiding behind pillar and waiting next to a series of arches.",
  },
  {
    id: 75,
    title: "Melody I",
    full: `${BASE}/img/Env_Melody01_Fin.avif`,
    thumb: `${BASE}/img/thumb/Env_Melody01_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Melody embodying Girl with the Dragon Tattoo.",
    alt: "Woman with gauze bandaged hand sitting on guard rail next to river.",
  },
  {
    id: 76,
    title: "Melody II",
    full: `${BASE}/img/Env_Melody02_Fin.avif`,
    thumb: `${BASE}/img/thumb/Env_Melody02_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Melody embodying Girl with the Dragon Tattoo.",
    alt: "Woman with bandaged hand sitting on park bench in front of Manhattan skyline.",
  },
  {
    id: 77,
    title: "Monica I",
    full: `${BASE}/img/Cinema_Monica_W.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Monica_W.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Monica embodying The Double Life of Veronique.",
    alt: "Woman on park bench contemplating.",
  },
  {
    id: 78,
    title: "Monica II",
    full: `${BASE}/img/Cinema_Monica2_Fin.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Monica2_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Monica embodying The Double Life of Veronique.",
    alt: "Woman in Union Square emoting.",
  },
  {
    id: 79,
    title: "Sean I",
    full: `${BASE}/img/Cinema_Sean_01_Fin.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Sean_01_Fin.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Sean embodying Chinatown",
    alt: "man with bloodied bandage on his nose leaning against an elevator bank.",
  },
  {
    id: 80,
    title: "Sean II",
    full: `${BASE}/img/Cinema_Sean_02_Fin-2.avif`,
    thumb: `${BASE}/img/thumb/Cinema_Sean_02_Fin-2.avif`,
    category: ["digital", "color", "proj:cinematic"],
    description: "Sean embodying Chinatown",
    alt: "Man standing on a winding stair.",
  },
  {
    id: 81,
    title: "PHI Training 01",
    full: `${BASE}/img/PHI_office-213.avif`,
    thumb: `${BASE}/img/thumb/PHI_office-213.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training entrance",
    alt: "Entryway of a medical office",
  },
  {
    id: 82,
    title: "PHI Training 02",
    full: `${BASE}/img/PHI_office-407.avif`,
    thumb: `${BASE}/img/thumb/PHI_office-407.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training offices",
    alt: "Cubicle with people working",
  },
  {
    id: 83,
    title: "PHI Training 03",
    full: `${BASE}/img/PHI_office-522.avif`,
    thumb: `${BASE}/img/thumb/PHI_office-522.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training offices",
    alt: "People working at their desks.",
  },
  {
    id: 84,
    title: "PHI Training 04",
    full: `${BASE}/img/PHI_office-534.avif`,
    thumb: `${BASE}/img/thumb/PHI_office-534.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training department reception desk.",
    alt: "Woman standing at a reception desk in a medical office.",
  },
  {
    id: 85,
    title: "PHI Training 05",
    full: `${BASE}/img/PHI_office-600.avif`,
    thumb: `${BASE}/img/thumb/PHI_office-600.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training offices",
    alt: "People working in front of their computers.",
  },
  {
    id: 86,
    title: "PHI Training 06",
    full: `${BASE}/img/PHI_Training-144.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-144.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training class",
    alt: "Nurses in a class room setting",
  },
  {
    id: 87,
    title: "PHI Training 07",
    full: `${BASE}/img/PHI_Training-152.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-152.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Teacher at the head of a class.",
  },
  {
    id: 88,
    title: "PHI Training 08",
    full: `${BASE}/img/PHI_Training-155.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-155.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom.",
    alt: "Teacher at the head of a classroom.",
  },
  {
    id: 89,
    title: "PHI Training 09",
    full: `${BASE}/img/PHI_Training-159.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-159.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Teacher at the head of a classroom.",
  },
  {
    id: 90,
    title: "PHI Training 10",
    full: `${BASE}/img/PHI_Training-174.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-174.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Teacher at the head of a classroom.",
  },
  {
    id: 91,
    title: "PHI Training 11",
    full: `${BASE}/img/PHI_Training-191.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-191.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Teacher at the head of a classroom.",
  },
  {
    id: 92,
    title: "PHI Training 12",
    full: `${BASE}/img/PHI_Training-197.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-197.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Teacher at the head of a classroom.",
  },
  {
    id: 93,
    title: "PHI Training 13",
    full: `${BASE}/img/PHI_Training-210.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-210.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Woman raising her hand in a classroom setting.",
  },
  {
    id: 94,
    title: "PHI Training 14",
    full: `${BASE}/img/PHI_Training-214.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-214.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "A classroom of nursing students.",
  },
  {
    id: 95,
    title: "PHI Training 15",
    full: `${BASE}/img/PHI_Training-216.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-216.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Nursing students at their desk",
  },
  {
    id: 96,
    title: "PHI Training 16",
    full: `${BASE}/img/PHI_Training-222.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-222.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Nursing students conversing at their desk.",
  },
  {
    id: 97,
    title: "PHI Training 17",
    full: `${BASE}/img/PHI_Training-312.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-312.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom.",
    alt: "Nursing students training with equipment.",
  },
  {
    id: 98,
    title: "PHI Training 18",
    full: `${BASE}/img/PHI_Training-331.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-331.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom.",
    alt: "Nursing students training with equipment.",
  },
  {
    id: 99,
    title: "PHI Training 19",
    full: `${BASE}/img/PHI_Training-335.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-335.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom.",
    alt: "Nursing students training with equipment.",
  },
  {
    id: 100,
    title: "PHI Training 20",
    full: `${BASE}/img/PHI_Training-392.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-392.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom.",
    alt: "Nursing student training with blood pressure cuff.",
  },
  {
    id: 101,
    title: "PHI Training 21",
    full: `${BASE}/img/PHI_Training-402.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-402.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Nurses training on a bed-bound patient",
  },
  {
    id: 102,
    title: "PHI Training 22",
    full: `${BASE}/img/PHI_Training-413.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-413.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Nurses training on a bed-bound patient",
  },
  {
    id: 103,
    title: "PHI Training 23",
    full: `${BASE}/img/PHI_Training-415.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-415.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom",
    alt: "Nurses training on a bed-bound patient",
  },
  {
    id: 104,
    title: "PHI Training 24",
    full: `${BASE}/img/PHI_Training-505.avif`,
    thumb: `${BASE}/img/thumb/PHI_Training-505.avif`,
    category: ["digital", "color", "medical"],
    description: "PHI Training classroom.",
    alt: "Nursing students training with equipment.",
  },
  {
    id: 105,
    title: "Wiley Blackwell 01",
    full: `${BASE}/img/Med_F04_44.avif`,
    thumb: `${BASE}/img/thumb/Med_F04_44.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 106,
    title: "Wiley Blackwell 02",
    full: `${BASE}/img/Med_F08_88D.avif`,
    thumb: `${BASE}/img/thumb/Med_F08_88D.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 107,
    title: "WileyBlackwell_03",
    full: `${BASE}/img/Med_F08_89.avif`,
    thumb: `${BASE}/img/thumb/Med_F08_89.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 108,
    title: "WileyBlackwell_04",
    full: `${BASE}/img/Med_F08_94.jpg`,
    thumb: `${BASE}/img/thumb/Med_F08_94.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 109,
    title: "WileyBlackwell_05",
    full: `${BASE}/img/Med_F08_110A.avif`,
    thumb: `${BASE}/img/thumb/Med_F08_110A.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 110,
    title: "WileyBlackwell_06",
    full: `${BASE}/img/Med_F10_45.avif`,
    thumb: `${BASE}/img/thumb/Med_F10_45.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 111,
    title: "WileyBlackwell_07",
    full: `${BASE}/img/Med_F11_68A.jpg`,
    thumb: `${BASE}/img/thumb/Med_F11_68A.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 112,
    title: "WileyBlackwell_08",
    full: `${BASE}/img/Med_F12_73A.avif`,
    thumb: `${BASE}/img/thumb/Med_F12_73A.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 113,
    title: "WileyBlackwell_09",
    full: `${BASE}/img/Med_F13_94.avif`,
    thumb: `${BASE}/img/thumb/Med_F13_94.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 114,
    title: "WileyBlackwell_010",
    full: `${BASE}/img/Med_F13_96.avif`,
    thumb: `${BASE}/img/thumb/Med_F13_96.avif`,
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
    alt: "Physical therapist illustrating therapy techniques",
  },
  {
    id: 115,
    title: "Abstract_01",
    full: `${BASE}/img/PinholeAbstracts-1.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-1.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 116,
    title: "Abstract 02",
    full: `${BASE}/img/PinholeAbstracts-2.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-2.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 117,
    title: "Abstract 03",
    full: `${BASE}/img/PinholeAbstracts-3.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-3.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 118,
    title: "Abstract 04",
    full: `${BASE}/img/PinholeAbstracts-4.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-4.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 119,
    title: "Abstract 05",
    full: `${BASE}/img/PinholeAbstracts-5.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-5.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 120,
    title: "Abstract 06",
    full: `${BASE}/img/PinholeAbstracts-6.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-6.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 121,
    title: "Abstract 07",
    full: `${BASE}/img/PinholeAbstracts-7.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-7.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 122,
    title: "Abstract 08",
    full: `${BASE}/img/PinholeAbstracts-8.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-8.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 123,
    title: "Abstract 09",
    full: `${BASE}/img/PinholeAbstracts-9.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-9.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 124,
    title: "Abstract 10",
    full: `${BASE}/img/PinholeAbstracts-10.avif`,
    thumb: `${BASE}/img/thumb/PinholeAbstracts-10.avif`,
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
    alt: "Colorful abstract shapes",
  },
  {
    id: 125,
    title: "Tryptic I",
    full: `${BASE}/img/Abs_Tryptic.avif`,
    thumb: `${BASE}/img/thumb/Abs_Tryptic.avif`,
    category: ["digital", "color", "abstract"],
    description: "Triptic Abstracts",
    alt: "Tryptic of colorful abstract shapes.",
  },
  {
    id: 126,
    title: "Tryptic II",
    full: `${BASE}/img/Abs_Narrative02.avif`,
    thumb: `${BASE}/img/thumb/Abs_Narrative02.avif`,
    category: ["digital", "color", "abstract"],
    description: "Triptic Abstracts",
    alt: "Tryptic of colorful abstract shapes.",
  },
  {
    id: 127,
    title: "Tryptic III",
    full: `${BASE}/img/Abs_Narrative03.avif`,
    thumb: `${BASE}/img/thumb/Abs_Narrative03.avif`,
    category: ["digital", "color", "abstract"],
    description: "Triptic Abstracts",
    alt: "Tryptic of colorful abstract shapes.",
  },
  {
    id: 128,
    title: "BeautyShot_01",
    full: `${BASE}/img/Beaut_DesantiBeauty_0130_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0130_Tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 129,
    title: "BeautyShot_02",
    full: `${BASE}/img/Beaut_DesantiBeauty_0214_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0214_Tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 130,
    title: "BeautyShot_03",
    full: `${BASE}/img/Beaut_DesantiBeauty_0301_Tag2.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0301_Tag2.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 131,
    title: "BeautyShot_04",
    full: `${BASE}/img/Beaut_DesantiBeauty_0330_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0330_Tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 132,
    title: "BeautyShot_05",
    full: `${BASE}/img/Beaut_DesantiBeauty_0390_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0390_Tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 133,
    title: "BeautyShot_06",
    full: `${BASE}/img/Beaut_DesantiBeauty_0447_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0447_Tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 134,
    title: "BeautyShot_07",
    full: `${BASE}/img/Beaut_DesantiBeauty_0077_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_DesantiBeauty_0077_Tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 135,
    title: "BeautyShot_08",
    full: `${BASE}/img/Beaut_Key_215_Tag2.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_Key_215_Tag2.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 136,
    title: "BeautyShot_09",
    full: `${BASE}/img/Beaut_Caya_119_tag.jpg`,
    thumb: `${BASE}/img/thumb/Beaut_Caya_119_tag.avif`,
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
    alt: "Headshot of woman",
  },
  {
    id: 137,
    title: "Fashion_Men",
    full: `${BASE}/img/MFash_Devand_3.avif`,
    thumb: `${BASE}/img/thumb/MFash_Devand_3.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 138,
    title: "Fashion_Men_01",
    full: `${BASE}/img/MFash_Quincy_1764_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Quincy_1764_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 139,
    title: "Fashion_Men_02",
    full: `${BASE}/img/MFash_Quincy_084_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Quincy_084_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 140,
    title: "Fashion_Men_03",
    full: `${BASE}/img/MFash_Quincy_183_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Quincy_183_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 141,
    title: "Fashion_Men_04",
    full: `${BASE}/img/MFash_Quincy_242_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Quincy_242_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 142,
    title: "Fashion_Men_05",
    full: `${BASE}/img/MFash_Tie_064_Tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Tie_064_Tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 143,
    title: "Fashion_Men_06",
    full: `${BASE}/img/MFash_Tie_153_tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Tie_153_tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 144,
    title: "Fashion_Men_06",
    full: `${BASE}/img/MFash_Tie_203_tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Tie_203_tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 145,
    title: "Fashion_Men_07",
    full: `${BASE}/img/MFash_20091025_IMG_3317.jpg`,
    thumb: `${BASE}/img/thumb/MFash_20091025_IMG_3317.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 146,
    title: "Fashion_Men_08",
    full: `${BASE}/img/MFash_20091025_IMG_3417.jpg`,
    thumb: `${BASE}/img/thumb/MFash_20091025_IMG_3417.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 147,
    title: "Fashion_Men_09",
    full: `${BASE}/img/MFash_Is_0151_700tag.avif`,
    thumb: `${BASE}/img/thumb/MFash_Is_0151_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 148,
    title: "Fashion_Men_10",
    full: `${BASE}/img/MFash_Is_0188_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Is_0188_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 149,
    title: "Fashion_Men_11",
    full: `${BASE}/img/MFash_Is_0305_700tag2.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Is_0305_700tag2.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 150,
    title: "Fashion_Men_12",
    full: `${BASE}/img/MFash_Is_0339_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Is_0339_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 151,
    title: "Fashion_Men_13",
    full: `${BASE}/img/MFash_Is_0262_700tag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Is_0262_700tag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 152,
    title: "Fashion_Men_14",
    full: `${BASE}/img/MFash_Kerwin_0066_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/MFash_Kerwin_0066_WebTag.avif`,
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
    alt: "Man showing off men's fashion",
  },
  {
    id: 153,
    title: "Fashion_Women_01",
    full: `${BASE}/img/WFash_Woods1.avif`,
    thumb: `${BASE}/img/thumb/WFash_Woods1.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 154,
    title: "Fashion_Women_02",
    full: `${BASE}/img/WFash_Woods_0151_FinTag.avif`,
    thumb: `${BASE}/img/thumb/WFash_Woods_0151_FinTag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 155,
    title: "Fashion_Women_03",
    full: `${BASE}/img/WFash_Woods_0013_FinTag.avif`,
    thumb: `${BASE}/img/thumb/WFash_Woods_0013_FinTag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 156,
    title: "Fashion_Women_04",
    full: `${BASE}/img/WFash_PandP_0048_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_PandP_0048_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 157,
    title: "Fashion_Women_05",
    full: `${BASE}/img/WFash_PandP_0246_700tag.avif`,
    thumb: `${BASE}/img/thumb/WFash_PandP_0246_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 158,
    title: "Fashion_Women_06",
    full: `${BASE}/img/WFash_PandP_0292_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_PandP_0292_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 159,
    title: "Fashion_Women_07",
    full: `${BASE}/img/WFash_HushMag01_0150_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_HushMag01_0150_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 160,
    title: "Fashion_Women_22",
    full: `${BASE}/img/WFash_Liq_0406_700tag.avif`,
    thumb: `${BASE}/img/thumb/WFash_Liq_0406_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 161,
    title: "Fashion_Women_20",
    full: `${BASE}/img/WFash_Liq_0278_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Liq_0278_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 162,
    title: "Fashion_Women_21",
    full: `${BASE}/img/WFash_Liq_0313_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Liq_0313_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 163,
    title: "Fashion_Women_08",
    full: `${BASE}/img/WFash_Hush_Pool_304_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_304_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 164,
    title: "Fashion_Women_09",
    full: `${BASE}/img/WFash_Hush_Pool_415_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_415_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 165,
    title: "Fashion_Women_10",
    full: `${BASE}/img/WFash_Hush_Pool_485_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_485_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 166,
    title: "Fashion_Women_11",
    full: `${BASE}/img/WFash_Hush_Pool_407_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_407_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 167,
    title: "Fashion_Women_12",
    full: `${BASE}/img/WFash_Hush_Pool_205_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_205_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 168,
    title: "Fashion_Women_10",
    full: `${BASE}/img/WFash_Hush_Pool_221_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_221_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 169,
    title: "Fashion_Women_11",
    full: `${BASE}/img/WFash_Theate_0345_Web.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Theate_0345_Web.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 170,
    title: "Fashion_Women_28",
    full: `${BASE}/img/WFash_MeMag_126_700WebTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_MeMag_126_700WebTag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 171,
    title: "Fashion_Women_29",
    full: `${BASE}/img/WFash_MeMag_174_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_MeMag_174_WebTag.avif`,
    category: ["digital", "b&w", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 172,
    title: "Fashion_Women_12",
    full: `${BASE}/img/WFash_Hush_Pool_435_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Hush_Pool_435_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 173,
    title: "Fashion_Women_13",
    full: `${BASE}/img/WFash_FilmNOIR_117_FinTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_FilmNOIR_117_FinTag.avif`,
    category: ["digital", "b&w", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 174,
    title: "Fashion_Women_14",
    full: `${BASE}/img/WFash_FilmNoir2_Filim_Fin_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_FilmNoir2_Filim_Fin_WebTag.avif`,
    category: ["digital", "b&w", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 175,
    title: "Fashion_Women_15",
    full: `${BASE}/img/WFash_FilmNoir3_Film_Fin_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_FilmNoir3_Film_Fin_WebTag.avif`,
    category: ["digital", "b&w", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 176,
    title: "Fashion_Women_17",
    full: `${BASE}/img/WFash_LilBD_060_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_LilBD_060_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 177,
    title: "Fashion_Women_18",
    full: `${BASE}/img/WFash_LilBD_163_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_LilBD_163_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 178,
    title: "Fashion_Women_19",
    full: `${BASE}/img/WFash_LilBD_190_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_LilBD_190_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 179,
    title: "Fashion_Women_23",
    full: `${BASE}/img/WFash_Theate_0108_Web.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Theate_0108_Web.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 180,
    title: "Fashion_Women_24",
    full: `${BASE}/img/WFash_Theate_0394_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Theate_0394_WebTag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 181,
    title: "Fashion_Women_25",
    full: `${BASE}/img/WFash_Bri_026_700tag.avif`,
    thumb: `${BASE}/img/thumb/WFash_Bri_026_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 182,
    title: "Fashion_Women_26",
    full: `${BASE}/img/WFash_Bri_471_700tag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_Bri_471_700tag.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 183,
    title: "Fashion_Women_27",
    full: `${BASE}/img/WFash_FF_0102_Fin.jpg`,
    thumb: `${BASE}/img/thumb/WFash_FF_0102_Fin.avif`,
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 184,
    title: "Fashion_Women_16",
    full: `${BASE}/img/WFash_WoodsFilm01_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/WFash_WoodsFilm01_WebTag.avif`,
    category: ["film", "b&w", "fashion:women"],
    description: "Women's Fashion",
    alt: "Woman showing off women's fashion",
  },
  {
    id: 185,
    title: "Korveil",
    full: `${BASE}/img/Mus_Korveil.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Korveil.avif`,
    category: ["digital", "color", "music"],
    description: "Korveil portrait",
    alt: "Man with hat sitting in profile in front of black backdrop.",
  },
  {
    id: 186,
    title: "Cache City",
    full: `${BASE}/img/Mus_CacheCity.avif`,
    thumb: `${BASE}/img/thumb/Mus_CacheCity.avif`,
    category: ["digital", "color", "music"],
    description: "Cache City portrait",
    alt: "Three men in an alley in front of the Chicago skyline.",
  },
  {
    id: 187,
    title: "Jaeno",
    full: `${BASE}/img/Mus_Jaeno.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Jaeno.avif`,
    category: ["digital", "color", "music"],
    description: "Jaeno portrait",
    alt: "Man standing in front of column of a tressel bridge.",
  },
  {
    id: 188,
    title: "Dave The Producer",
    full: `${BASE}/img/Mus_DaveTheProducer.jpg`,
    thumb: `${BASE}/img/thumb/Mus_DaveTheProducer.avif`,
    category: ["digital", "color", "music"],
    description: "Dave the Producer portrait.",
    alt: "Man in front of downtown Chicago skyline at night.",
  },
  {
    id: 189,
    title: "Selina",
    full: `${BASE}/img/Mus_Selina_0452_tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Selina_0452_tag.avif`,
    category: ["digital", "color", "music"],
    description: "Selina portrait",
    alt: "Woman in country hippy outfit sitting with acoustic guitar in the woods.",
  },
  {
    id: 190,
    title: "FAN - Kenneth",
    full: `${BASE}/img/Mus_FAN_341_W2WebTag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_FAN_341_W2WebTag.avif`,
    category: ["digital", "color", "music"],
    description: "Kenneth portrait",
    alt: "Man with green headwrap standing in profile.",
  },
  {
    id: 191,
    title: "FAN - Herb",
    full: `${BASE}/img/Mus_FAN_0110_W2_WebTag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_FAN_0110_W2_WebTag.avif`,
    category: ["digital", "color", "music"],
    description: "Herb portrait",
    alt: "Man with dreads in his face standing in profile.",
  },
  {
    id: 192,
    title: "Korveil II",
    full: `${BASE}/img/Mus_Korveil_515_700tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Korveil_515_700tag.avif`,
    category: ["digital", "color", "music"],
    description: "Korveil portrait",
    alt: "Man sitting in chair caressing a woman's leg.",
  },
  {
    id: 193,
    title: "Cherisa",
    full: `${BASE}/img/Mus_CherisaFinal_Web.avif`,
    thumb: `${BASE}/img/thumb/Mus_CherisaFinal_Web.avif`,
    category: ["digital", "color", "music"],
    description: "Cherisa portrait",
    alt: "Woman in sunglasses and neckscarf standing in front of graffitd wall.",
  },
  {
    id: 194,
    title: "Hannibal",
    full: `${BASE}/img/Mus_Hannibal_564_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Hannibal_564_Tag.avif`,
    category: ["digital", "b&w", "music"],
    description: "Hannibal portrait",
    alt: "Man in cap with flags over his shoulder with his back to camera.",
  },
  {
    id: 195,
    title: "Ignacio",
    full: `${BASE}/img/Mus_IgnacioPortrait---WebTag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_IgnacioPortrait---WebTag.avif`,
    category: ["digital", "color", "music"],
    description: "Ignacio portrait",
    alt: "Man with hair bun playing drums.",
  },
  {
    id: 196,
    title: "Jaeno II",
    full: `${BASE}/img/Mus_Jaeno_0091_Webtag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Jaeno_0091_Webtag.avif`,
    category: ["digital", "color", "music"],
    description: "Jaeno portrait",
    alt: "Man in plaid shirt and black jacket standing on tressle bridge.",
  },
  {
    id: 197,
    title: "Rayshawn I",
    full: `${BASE}/img/Mus_Rayshawn-2863-Webtag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Rayshawn-2863-Webtag.avif`,
    category: ["digital", "color", "music"],
    description: "Rayshawn portrait",
    alt: "Man in baseball cap and sunglass in profile on black backdrop.",
  },
  {
    id: 198,
    title: "Rayshawn II",
    full: `${BASE}/img/Mus_Rayshawn-2898---Webtag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Rayshawn-2898---Webtag.avif`,
    category: ["digital", "color", "music"],
    description: "Rayshawn portrait II",
    alt: "Man in cap, sunglasses, and hoodie with the hood up.",
  },
  {
    id: 199,
    title: "TreZure",
    full: `${BASE}/img/Mus_TreZure_2921-WebTag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_TreZure_2921-WebTag.avif`,
    category: ["digital", "color", "music"],
    description: "Treazure portrait",
    alt: "Woman with short cropped hair in a sparkly environment.",
  },
  {
    id: 200,
    title: "Xodus I",
    full: `${BASE}/img/Mus_Xodus_0224_Tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Xodus_0224_Tag.avif`,
    category: ["digital", "b&w", "music"],
    description: "Xodus portrait I",
    alt: "Man with dreds being tossed in the air while in profile.",
  },
  {
    id: 201,
    title: "Xodus II",
    full: `${BASE}/img/Mus_Xodus_0333_Fin-Tag.jpg`,
    thumb: `${BASE}/img/thumb/Mus_Xodus_0333_Fin-Tag.avif`,
    category: ["digital", "b&w", "music"],
    description: "Xodus portrait",
    alt: "Man with paint on his face, wearing knit hat, and his hands at the side of his face.",
  },
  {
    id: 202,
    title: "Plastic Boots",
    full: `${BASE}/img/Mus_PlasticBoots.avif`,
    thumb: `${BASE}/img/thumb/Mus_PlasticBoots.avif`,
    category: ["digital", "color", "music"],
    description: "Plastic Boots portrait.",
    alt: "Three men standing in front of a cloudy, overcast, sky.",
  },
  {
    id: 203,
    title: "Retouch 01",
    full: `${BASE}/img/Retouch_Quincy-Touch Sample.jpg`,
    thumb: `${BASE}/img/thumb/Retouch_Quincy-Touch Sample.avif`,
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample 1",
    alt: "Before and after of retouching samples of man with neck scarf.",
  },
  {
    id: 204,
    title: "Retouch 02",
    full: `${BASE}/img/Retouch_MeMag_126_TouchSamp.jpg`,
    thumb: `${BASE}/img/thumb/Retouch_MeMag_126_TouchSamp.avif`,
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample 2",
    alt: "Before and after retouching examples of woman with hand touching face in pink dress.",
  },
  {
    id: 205,
    title: "Retouch 03",
    full: `${BASE}/img/Retouch_LilBD_060_TouchSamp.jpg`,
    thumb: `${BASE}/img/thumb/Retouch_LilBD_060_TouchSamp.avif`,
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample 3",
    alt: "Before and after retouching examples of a woman in front of red fabric surrounded by cameras.",
  },
  {
    id: 206,
    title: "Retouch 04",
    full: `${BASE}/img/Retouch_Key_215_TouchSamp.jpg`,
    thumb: `${BASE}/img/thumb/Retouch_Key_215_TouchSamp.avif`,
    category: ["digital", "b&w", "retouching"],
    description: "Retouching Sample 4",
    alt: "Before and after retouching examples of a woman standing in front of backdrop with hands on head.",
  },
  {
    id: 207,
    title: "Retouch 05",
    full: `${BASE}/img/Retouch_Caya_095_TouchSample.jpg`,
    thumb: `${BASE}/img/thumb/Retouch_Caya_095_TouchSample.avif`,
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample 5",
    alt: "Before and after retouching examples of a woman wearing hat and jeweled necklace.",
  },
  {
    id: 208,
    title: "Retouch 06",
    full: `${BASE}/img/Retouch_Bri_026_TouchSamp.avif`,
    thumb: `${BASE}/img/thumb/Retouch_Bri_026_TouchSamp.avif`,
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample 6",
    alt: "Before and after retouching examples of a woman in a dress standing in front of a table.",
  },
  {
    id: 209,
    title: "GlassBlower 1",
    full: `${BASE}/img/GlassBlo_01.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_01.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glass blower tools on a wooden crate.",
  },
  {
    id: 210,
    title: "GlassBlower 2",
    full: `${BASE}/img/GlassBlo_02.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_02.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man gesturing in front of glass blowing kilm",
  },
  {
    id: 211,
    title: "GlassBlower 3",
    full: `${BASE}/img/GlassBlo_03.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_03.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Rows of cooling chests",
  },
  {
    id: 212,
    title: "GlassBlower 4",
    full: `${BASE}/img/GlassBlo_04.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_04.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Sketchpad of potential glass blowing designs on on table.",
  },
  {
    id: 213,
    title: "GlassBlower 5",
    full: `${BASE}/img/GlassBlo_05.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_05.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man sitting at glass blowing bench preparing tools.",
  },
  {
    id: 214,
    title: "GlassBlower 6",
    full: `${BASE}/img/GlassBlo_06.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_06.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Row of firing kilms.",
  },
  {
    id: 215,
    title: "GlassBlower 7",
    full: `${BASE}/img/GlassBlo_07.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_07.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glass blowing assitant holding out tools.",
  },
  {
    id: 216,
    title: "GlassBlower 8",
    full: `${BASE}/img/GlassBlo_08.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_08.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man firing a glowing ball of glass at the end of a pike in a kilm.",
  },
  {
    id: 217,
    title: "GlassBlower 9",
    full: `${BASE}/img/GlassBlo_09.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_09.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man cooling pike in a water device.",
  },
  //

  {
    id: 218,
    title: "GlassBlower 10",
    full: `${BASE}/img/GlassBlo_10.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_10.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man blowing air through the end of a pike into molten glass.",
  },
  {
    id: 219,
    title: "GlassBlower 11",
    full: `${BASE}/img/GlassBlo_11.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_11.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man firing glass in a kilm.",
  },
  {
    id: 220,
    title: "GlassBlower 12",
    full: `${BASE}/img/GlassBlo_12.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_12.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man looking off frame with assistant behind him.",
  },
  {
    id: 221,
    title: "GlassBlower 13",
    full: `${BASE}/img/GlassBlo_13.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_13.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Molten glass in front of kilm.",
  },
  {
    id: 222,
    title: "GlassBlower 14",
    full: `${BASE}/img/GlassBlo_14.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_14.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Female assistant rolling molten glass in blue coloring.",
  },
  {
    id: 223,
    title: "GlassBlower 15",
    full: `${BASE}/img/GlassBlo_15.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_15.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Close up of molten glass being rolled in blue coloring.",
  },
  {
    id: 224,
    title: "GlassBlower 16",
    full: `${BASE}/img/GlassBlo_16.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_16.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Molten glass bing pour on an expanded form.",
  },
  {
    id: 225,
    title: "GlassBlower 17",
    full: `${BASE}/img/GlassBlo_17.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_17.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Close up of molten blown glass being shaped with tongs.",
  },
  {
    id: 226,
    title: "GlassBlower 18",
    full: `${BASE}/img/GlassBlo_18.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_18.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glass shape being molded by a burnt flat wooden plank.",
  },
  {
    id: 227,
    title: "GlassBlower 19",
    full: `${BASE}/img/GlassBlo_19.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_19.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Close up of male glass blower wearing saftey glasses.",
  },
  {
    id: 228,
    title: "GlassBlower 20",
    full: `${BASE}/img/GlassBlo_20.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_20.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Shaped molten glass in a glowing kilm.",
  },
  {
    id: 229,
    title: "GlassBlower 21",
    full: `${BASE}/img/GlassBlo_21.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_21.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glassblower detailing a glass for with a molten glass ring.",
  },
  {
    id: 230,
    title: "GlassBlower 22",
    full: `${BASE}/img/GlassBlo_22.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_22.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glassblower shaping molten ring with a cone shaped tool.",
  },
  {
    id: 231,
    title: "GlassBlower 23",
    full: `${BASE}/img/GlassBlo_23.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_23.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glassblower giving glass form to assistant wearing gigantic oven mitts.",
  },
  {
    id: 232,
    title: "GlassBlower 24",
    full: `${BASE}/img/GlassBlo_24.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_24.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Female assistant placing a glass form in a cooling cabinet.",
  },
  {
    id: 233,
    title: "GlassBlower 25",
    full: `${BASE}/img/GlassBlo_25.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_25.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Hand shaping molten glass in a wet wooden ladel.",
  },
  {
    id: 234,
    title: "GlassBlower 26",
    full: `${BASE}/img/GlassBlo_26.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_26.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Close up of wooden ladel.",
  },
  {
    id: 235,
    title: "GlassBlower 27",
    full: `${BASE}/img/GlassBlo_27.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_27.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man using burnt newspaper to mold molten glass with his hands.",
  },
  {
    id: 236,
    title: "GlassBlower 28",
    full: `${BASE}/img/GlassBlo_28.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_28.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man blowing through the end of a pike to shape molten glass in a mold.",
  },
  {
    id: 237,
    title: "GlassBlower 29",
    full: `${BASE}/img/GlassBlo_29.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_29.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Extended measuring tape being compared to blown glass.",
  },
  {
    id: 238,
    title: "GlassBlower 30",
    full: `${BASE}/img/GlassBlo_30.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_30.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man measuring pincers against measuring tape.",
  },
  {
    id: 239,
    title: "GlassBlower 31",
    full: `${BASE}/img/GlassBlo_31.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_31.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man and assistant pouring molten run off glass into a bucket.",
  },
  {
    id: 240,
    title: "GlassBlower 32",
    full: `${BASE}/img/GlassBlo_32.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_32.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Close up of face shild and oven mitts for handling glass.",
  },
  {
    id: 241,
    title: "GlassBlower 33",
    full: `${BASE}/img/GlassBlo_33.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_33.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glassblower and assistant watching the glass in a kilm.",
  },
  {
    id: 242,
    title: "GlassBlower 34",
    full: `${BASE}/img/GlassBlo_34.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_34.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Close up of glass in mold.",
  },
  {
    id: 243,
    title: "GlassBlower 35",
    full: `${BASE}/img/GlassBlo_35.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_35.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Glassblower using a cutter to cut a tube of glass.",
  },
  {
    id: 244,
    title: "GlassBlower 36",
    full: `${BASE}/img/GlassBlo_36.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_36.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Man looking down at molten glass at the end of a pike.",
  },
  {
    id: 245,
    title: "GlassBlower 37",
    full: `${BASE}/img/GlassBlo_37.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_37.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Several pikes in a heating furnace.",
  },
  {
    id: 246,
    title: "GlassBlower 38",
    full: `${BASE}/img/GlassBlo_38.avif`,
    thumb: `${BASE}/img/thumb/GlassBlo_38.avif`,
    category: ["digital", "color", "story:glassblower"],
    description: "Glass Blower Story",
    alt: "Broken glass from a failed glass shaping.",
  },
  {
    id: 247,
    title: "Street 1",
    full: `${BASE}/img/Street_01.avif`,
    thumb: `${BASE}/img/thumb/Street_01.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Two construction workers examinging a co-worker who has an injury.",
  },
  {
    id: 248,
    title: "Street 2",
    full: `${BASE}/img/Street_02.avif`,
    thumb: `${BASE}/img/thumb/Street_02.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Man standing in a steam cloud coming from the ground.",
  },
  {
    id: 249,
    title: "Street 4",
    full: `${BASE}/img/Street_04.avif`,
    thumb: `${BASE}/img/thumb/Street_04.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "A traffic cone chained to a fire hydrant.",
  },
  {
    id: 250,
    title: "Street 19",
    full: `${BASE}/img/Street_19.avif`,
    thumb: `${BASE}/img/thumb/Street_19.avif`,
    category: ["digital", "color", "street"],
    description: "Street Photography",
    alt: "Old man framed by crowd with the word Advisor above his head.",
  },
  {
    id: 251,
    title: "Street 20",
    full: `${BASE}/img/Street_20.avif`,
    thumb: `${BASE}/img/thumb/Street_20.avif`,
    category: ["digital", "color", "street"],
    description: "Street Photography",
    alt: "Two poeple at a farmer's market facing each other and chewing on their thumbs.",
  },
  {
    id: 252,
    title: "Street 21",
    full: `${BASE}/img/Street_21.avif`,
    thumb: `${BASE}/img/thumb/Street_21.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Crowded train with people forcing their way on.",
  },
  {
    id: 253,
    title: "Street 5",
    full: `${BASE}/img/Street_05.avif`,
    thumb: `${BASE}/img/thumb/Street_05.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "A family wearing sunglasses framing maniquin heads wearing sunglasses.",
  },
  {
    id: 254,
    title: "Street 6",
    full: `${BASE}/img/Street_06.avif`,
    thumb: `${BASE}/img/thumb/Street_06.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Two people relaxing at a park. One wears a nurses outfit and the other wears a neck brace.",
  },
  {
    id: 255,
    title: "Street 7",
    full: `${BASE}/img/Street_07.avif`,
    thumb: `${BASE}/img/thumb/Street_07.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Woman whipsering into a phone with her hand over her face.",
  },
  {
    id: 256,
    title: "Street 8",
    full: `${BASE}/img/Street_08.avif`,
    thumb: `${BASE}/img/thumb/Street_08.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Man walking past a row of men sitting on the median of a street.",
  },
  {
    id: 257,
    title: "Street 9",
    full: `${BASE}/img/Street_09.avif`,
    thumb: `${BASE}/img/thumb/Street_09.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Dutch angle of a person sleeping on a park bench in Thinker pose.",
  },
  {
    id: 258,
    title: "Street 10",
    full: `${BASE}/img/Street_10.avif`,
    thumb: `${BASE}/img/thumb/Street_10.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Street vendor stairing off frame as customer talks to him.",
  },
  {
    id: 259,
    title: "Street 11",
    full: `${BASE}/img/Street_11.avif`,
    thumb: `${BASE}/img/thumb/Street_11.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Man smoking a cigarett with cast and man standing in the background.",
  },
  {
    id: 260,
    title: "Street 12",
    full: `${BASE}/img/Street_12.avif`,
    thumb: `${BASE}/img/thumb/Street_12.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Man in an ice cream truck yelling at a woman digging through trash as another man empties trash.",
  },
  {
    id: 261,
    title: "Street 13",
    full: `${BASE}/img/Street_13.avif`,
    thumb: `${BASE}/img/thumb/Street_13.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "City working working on electrical equipment coming out of the sewer.",
  },
  {
    id: 262,
    title: "Street 14",
    full: `${BASE}/img/Street_14.avif`,
    thumb: `${BASE}/img/thumb/Street_14.avif`,
    category: ["digital", "color", "street"],
    description: "Street Photography",
    alt: "Woman clutching white dog under a pink umbrella as they cross the street.",
  },
  {
    id: 263,
    title: "Street 15",
    full: `${BASE}/img/Street_15.avif`,
    thumb: `${BASE}/img/thumb/Street_15.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Two men wearing t-shirt with hands pointing, holding their arms out as a woman holds her hands up.",
  },
  {
    id: 264,
    title: "Street 16",
    full: `${BASE}/img/Street_16.avif`,
    thumb: `${BASE}/img/thumb/Street_16.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Man picking nose in profile.",
  },
  {
    id: 265,
    title: "Street 17",
    full: `${BASE}/img/Street_17.avif`,
    thumb: `${BASE}/img/thumb/Street_17.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Old man with a cactus wrapped in plastic wrap in a granny cart.",
  },
  {
    id: 266,
    title: "Street 18",
    full: `${BASE}/img/Street_18.avif`,
    thumb: `${BASE}/img/thumb/Street_18.avif`,
    category: ["digital", "b&w", "street"],
    description: "Street Photography",
    alt: "Man walking across a train platform.",
  },
  {
    id: 267,
    title: "Ariel",
    full: `${BASE}/img/Crump_Ariel_0076_1kTag.jpg`,
    thumb: `${BASE}/img/thumb/Crump_Ariel_0076_1kTag.avif`,
    category: ["film", "b&w", "studio"],
    description: "Crumpled Portrait",
    alt: "Woman staring into camera in front of black crumpled backdrop.",
  },
  {
    id: 268,
    title: "JC",
    full: `${BASE}/img/Crump_JC-port_0083_1kTag.jpg`,
    thumb: `${BASE}/img/thumb/Crump_JC-port_0083_1kTag.avif`,
    category: ["film", "b&w", "studio"],
    description: "Crumpled Portrait",
    alt: "Woman staring into camera in front of black crumpled backdrop.",
  },
  {
    id: 269,
    title: "Mishelle",
    full: `${BASE}/img/Crump_Mishelle_0034_Fin.avif`,
    thumb: `${BASE}/img/thumb/Crump_Mishelle_0034_Fin.avif`,
    category: ["film", "b&w", "studio"],
    description: "Crumpled Portrait",
    alt: "Woman staring into camera in front of black crumpled backdrop.",
  },
  {
    id: 270,
    title: "Rosie",
    full: `${BASE}/img/Crump_RosiePortrait_0108_1kTag.jpg`,
    thumb: `${BASE}/img/thumb/Crump_RosiePortrait_0108_1kTag.avif`,
    category: ["film", "b&w", "studio"],
    description: "Crumpled Portrait",
    alt: "Woman staring into camera in front of black crumpled backdrop.",
  },
  {
    id: 271,
    title: "Close Up Portrait 05",
    full: `${BASE}/img/Crump_RosiePortrait_0108_1kTag.jpg`,
    thumb: `${BASE}/img/thumb/Crump_RosiePortrait_0108_1kTag.avif`,
    category: ["digital", "color", "studio"],
    description: "Close Up Portrait",
  },
  {
    id: 272,
    title: "Caleb",
    full: `${BASE}/img/CU_Caleb.jpg`,
    thumb: `${BASE}/img/thumb/CU_Caleb.avif`,
    category: ["digital", "color", "studio"],
    description: "Close Up Portrait",
    alt: "An extreme close up of a bald man.",
  },
  {
    id: 273,
    title: "Felipe",
    full: `${BASE}/img/CU_Felipe.jpg`,
    thumb: `${BASE}/img/thumb/CU_Felipe.avif`,
    category: ["digital", "color", "studio"],
    description: "Close Up Portrait",
    alt: "An extreme close up of a man.",
  },
  {
    id: 274,
    title: "Mark",
    full: `${BASE}/img/CU_Mark.jpg`,
    thumb: `${BASE}/img/thumb/CU_Mark.avif`,
    category: ["digital", "color", "studio"],
    description: "Close Up Portrait",
    alt: "An extreme close up of a man.",
  },
  {
    id: 275,
    title: "Sam",
    full: `${BASE}/img/CU_Sam.jpg`,
    thumb: `${BASE}/img/thumb/CU_Sam.avif`,
    category: ["digital", "color", "studio"],
    alt: "An extreme close up of a man.",
  },
  {
    id: 276,
    title: "Tanya",
    full: `${BASE}/img/CU_Tanya3.jpg`,
    thumb: `${BASE}/img/thumb/CU_Tanya3.avif`,
    category: ["digital", "color", "studio"],
    alt: "An extreme close up of a woman.",
  },
];

export default photoCollection;
