// TODO: must add description per photo

const photoCollection = [
  {
    id: 1,
    title: "Cast and Crew 3",
    url: "/img/FullGroup_Web.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 31,
    title: "Pamela",
    url: "/img/Pamela.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 38,
    title: "Harry",
    url: "/img/HarryPortrait_Web.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 53,
    title: "Pla",
    url: "/img/Pla2.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 48,
    title: "Montse 2",
    url: "/img/Montse2.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 2,
    title: "Cast and Crew",
    url: "/img/PatrickJerry_Web.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 3,
    title: "Cast and Crew 2",
    url: "/img/TimMargret_Web.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },

  {
    id: 32,
    title: "Brennan",
    url: "/img/Brennan.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 33,
    title: "Chris Holmes",
    url: "/img/ChrisHolmes.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 34,
    title: "Chris Holmes 2",
    url: "/img/ChrisHolmes02.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 36,
    title: "Devand",
    url: "/img/Devand.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 37,
    title: "Dyanis",
    url: "/img/Dyanis.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 39,
    title: "Isabel",
    url: "/img/Isabel.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 40,
    title: "Jackie",
    url: "/img/Jackie.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 42,
    title: "Kim",
    url: "/img/Kim.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 44,
    title: "Lindsay",
    url: "/img/Lindsay.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 45,
    title: "Meghan",
    url: "/img/Meghan.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 46,
    title: "Michelle",
    url: "/img/Michelle.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 47,
    title: "Montse",
    url: "/img/Montse.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 49,
    title: "Mychal",
    url: "/img/Mychal.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },

  {
    id: 51,
    title: "Patrick M",
    url: "/img/PatrickMarlett.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 52,
    title: "PHI Team",
    url: "/img/PHI_Training.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 55,
    title: "Tanya",
    url: "/img/Tanya.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 56,
    title: "Tati",
    url: "/img/Tati.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 57,
    title: "Tyra",
    url: "/img/Tyra.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 58,
    title: "Yuri",
    url: "/img/Yuri.jpg",
    category: ["digital", "color", "environmental"],
    description: "This is the description.",
  },
  {
    id: 60,
    title: "Gianni",
    url: "/img/Gianni02_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 61,
    title: "Mark",
    url: "/img/MarkA_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 62,
    title: "Mentors & Peers",
    url: "/img/MentorAndPeers_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 63,
    title: "MentorsGroup",
    url: "/img/MentorsGroup_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 64,
    title: "Monica & Gianni",
    url: "/img/MonicaGianni_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 65,
    title: "Neko & Danasia",
    url: "/img/NekoDanasia_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 66,
    title: "Plyne Christian & Kevin",
    url: "/img/PlyneChristianKevin_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 67,
    title: "Rosemary",
    url: "/img/Rosemary_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 68,
    title: "Tiffany",
    url: "/img/Tiffany_Fin.jpg",
    category: ["film", "b&w", "studio", "4x5"],
    description: "This is the description.",
  },
  {
    id: 69,
    title: "Curved Path",
    url: "/img/CurvedPath01_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 70,
    title: "Night Shot",
    url: "/img/NightShot02_IMA_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 71,
    title: "Pink Stairs",
    url: "/img/PinkFlowers2_Fin.jpg",
    category: ["film", "color", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 72,
    title: "Ramp",
    url: "/img/RampBldg_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 73,
    title: "Rusty Wall at Sunset",
    url: "/img/RustyWall01_Fin.jpg",
    category: ["film", "color", "landscape", "4x5"],
    description: "This is the description.",
  },

  {
    id: 4,
    title: "Vestibule",
    url: "/img/Vestibule_1_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 5,
    title: "Lawn & Stairs",
    url: "/img/LawnStairs_1_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 6,
    title: "Greenhouse 3",
    url: "/img/Greenhouse3_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 7,
    title: "Greenhouse 2",
    url: "/img/Greenhouse02_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 8,
    title: "Fallen Tree",
    url: "/img/FallenTree.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 9,
    title: "City 2",
    url: "/img/City2_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 10,
    title: "Bikes",
    url: "/img/bikes_W.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 11,
    title: "3 Buildings",
    url: "/img/3Bldgs_Fin.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 12,
    title: "Two Arches",
    url: "/img/2Arches_1_WebTag_1500.jpg",
    category: ["film", "b&w", "landscape", "4x5"],
    description: "This is the description.",
  },
  {
    id: 13,
    title: "Ajsean 1",
    url: "/img/Ajsean_Fin01.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 14,
    title: "Ajsean 2",
    url: "/img/Ajsean_Fin02.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 15,
    title: "Christian 1",
    url: "/img/christian01_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 16,
    title: "Christian 2",
    url: "/img/Christian02_W.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 17,
    title: "Emily 1",
    url: "/img/Emily_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 18,
    title: "Emily 2",
    url: "/img/Emily02_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 19,
    title: "Federico 1",
    url: "/img/Federico_W_01.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 20,
    title: "Federico 2",
    url: "/img/Federico_Fin_02.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 21,
    title: "Lottie",
    url: "/img/Lottie_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 22,
    title: "Matheus",
    url: "/img/Matheus_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 23,
    title: "Melody 1",
    url: "/img/Melody01_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 24,
    title: "Melody 2",
    url: "/img/Melody02_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 25,
    title: "Monica 1",
    url: "/img/Monica_W.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 26,
    title: "Monica 2",
    url: "/img/Monica2_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 27,
    title: "Sean 1",
    url: "/img/Sean_01_Fin.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 28,
    title: "Sean 2",
    url: "/img/Sean_02_Fin-2.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 29,
    title: "Sean W",
    url: "/img/Sean_W_01.jpg",
    category: ["digital", "color", "proj:cinematic"],
    description: "This is the description.",
  },
  {
    id: 300,
    title: "WileyBlackwell_01",
    url: "/img/F04_44.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 301,
    title: "WileyBlackwell_02",
    url: "/img/F08_88D.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 302,
    title: "WileyBlackwell_03",
    url: "/img/F08_89.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 303,
    title: "WileyBlackwell_04",
    url: "/img/F08_94.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 304,
    title: "WileyBlackwell_05",
    url: "/img/F08_110A.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 305,
    title: "WileyBlackwell_06",
    url: "/img/F10_45.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 306,
    title: "WileyBlackwell_07",
    url: "/img/F11_68A.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 307,
    title: "WileyBlackwell_08",
    url: "/img/F12_73A.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 308,
    title: "WileyBlackwell_09",
    url: "/img/F13_94.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 309,
    title: "WileyBlackwell_010",
    url: "/img/F13_96.jpg",
    category: ["digital", "color", "medical"],
    description: "Physical Therapy Instruction",
  },
  {
    id: 310,
    title: "PHI_Training_01",
    url: "/img/PHI_office-213.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 311,
    title: "PHI_Training_02",
    url: "/img/PHI_office-407.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 312,
    title: "PHI_Training_03",
    url: "/img/PHI_office-522.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 313,
    title: "PHI_Training_04",
    url: "/img/PHI_office-534.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 314,
    title: "PHI_Training_05",
    url: "/img/PHI_office-600.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 315,
    title: "PHI_Training_06",
    url: "/img/PHI_Training-144.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 316,
    title: "PHI_Training_07",
    url: "/img/PHI_Training-152.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 317,
    title: "PHI_Training_08",
    url: "/img/PHI_Training-155.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 318,
    title: "PHI_Training_09",
    url: "/img/PHI_Training-159.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 319,
    title: "PHI_Training_10",
    url: "/img/PHI_Training-174.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 320,
    title: "PHI_Training_11",
    url: "/img/PHI_Training-191.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 321,
    title: "PHI_Training_12",
    url: "/img/PHI_Training-197.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 322,
    title: "PHI_Training_13",
    url: "/img/PHI_Training-210.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 323,
    title: "PHI_Training_14",
    url: "/img/PHI_Training-214.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 324,
    title: "PHI_Training_15",
    url: "/img/PHI_Training-216.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 325,
    title: "PHI_Training_16",
    url: "/img/PHI_Training-222.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 326,
    title: "PHI_Training_17",
    url: "/img/PHI_Training-312.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 327,
    title: "PHI_Training_18",
    url: "/img/PHI_Training-331.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 328,
    title: "PHI_Training_19",
    url: "/img/PHI_Training-335.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 329,
    title: "PHI_Training_20",
    url: "/img/PHI_Training-392.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 330,
    title: "PHI_Training_21",
    url: "/img/PHI_Training-402.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 331,
    title: "PHI_Training_22",
    url: "/img/PHI_Training-413.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 332,
    title: "PHI_Training_23",
    url: "/img/PHI_Training-415.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 333,
    title: "PHI_Training_24",
    url: "/img/PHI_Training-505.jpg",
    category: ["digital", "color", "medical"],
    description: "PHI Training",
  },
  {
    id: 334,
    title: "Abstract_01",
    url: "/img/PinholeAbstracts-1.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 335,
    title: "Abstract_02",
    url: "/img/PinholeAbstracts-2.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 336,
    title: "Abstract_03",
    url: "/img/PinholeAbstracts-3.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 335,
    title: "Abstract_04",
    url: "/img/PinholeAbstracts-4.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 336,
    title: "Abstract_05",
    url: "/img/PinholeAbstracts-5.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 337,
    title: "Abstract_06",
    url: "/img/PinholeAbstracts-6.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 338,
    title: "Abstract_07",
    url: "/img/PinholeAbstracts-7.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 339,
    title: "Abstract_08",
    url: "/img/PinholeAbstracts-8.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 340,
    title: "Abstract_09",
    url: "/img/PinholeAbstracts-9.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 341,
    title: "Abstract_10",
    url: "/img/PinholeAbstracts-10.jpg",
    category: ["digital", "color", "abstract"],
    description: "Pinhole Abstracts",
  },
  {
    id: 342,
    title: "Tryptic-01",
    url: "/img/Tryptic.jpg",
    category: ["digital", "color", "abstract"],
    description: "Triptic Abstracts",
  },
  {
    id: 343,
    title: "Tryptic-02",
    url: "/img/Narrative02.jpg",
    category: ["digital", "color", "abstract"],
    description: "Triptic Abstracts",
  },
  {
    id: 344,
    title: "Tryptic-03",
    url: "/img/Narrative03.jpg",
    category: ["digital", "color", "abstract"],
    description: "Triptic Abstracts",
  },
  {
    id: 346,
    title: "BeautyShot_02",
    url: "/img/DesantiBeauty_0130_Tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 347,
    title: "BeautyShot_03",
    url: "/img/DesantiBeauty_0214_Tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 348,
    title: "BeautyShot_04",
    url: "/img/DesantiBeauty_0301_Tag2.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 349,
    title: "BeautyShot_05",
    url: "/img/DesantiBeauty_0330_Tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 350,
    title: "BeautyShot_06",
    url: "/img/DesantiBeauty_0390_Tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 351,
    title: "BeautyShot_07",
    url: "/img/DesantiBeauty_0447_Tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 345,
    title: "BeautyShot_01",
    url: "/img/DesantiBeauty_0077_Tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 352,
    title: "BeautyShot_08",
    url: "/img/Key_215_Tag2.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 353,
    title: "BeautyShot_09",
    url: "/img/Caya_119_tag.jpg",
    category: ["digital", "color", "beauty", "studio"],
    description: "Beauty Shots",
  },
  {
    id: 354,
    title: "Fashion_Men_01",
    url: "/img/Quincy_1764_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 355,
    title: "Fashion_Men_02",
    url: "/img/Quincy_084_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 356,
    title: "Fashion_Men_03",
    url: "/img/Quincy_183_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 357,
    title: "Fashion_Men_04",
    url: "/img/Quincy_242_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 358,
    title: "Fashion_Men_05",
    url: "/img/Tie_064_Tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 359,
    title: "Fashion_Men_06",
    url: "/img/Tie_153_tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 360,
    title: "Fashion_Men_06",
    url: "/img/Tie_203_tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 361,
    title: "Fashion_Men_07",
    url: "/img/20091025_IMG_3317.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 362,
    title: "Fashion_Men_08",
    url: "/img/20091025_IMG_3417.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 363,
    title: "Fashion_Men_09",
    url: "/img/Is_0151_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 364,
    title: "Fashion_Men_10",
    url: "/img/Is_0188_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 365,
    title: "Fashion_Men_11",
    url: "/img/Is_0305_700tag2.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 366,
    title: "Fashion_Men_12",
    url: "/img/Is_0339_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 368,
    title: "Fashion_Men_13",
    url: "/img/Is_0262_700tag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 369,
    title: "Fashion_Men_14",
    url: "/img/Kerwin_0066_WebTag.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 370,
    title: "Fashion_Women_01",
    url: "/img/Woods1.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 371,
    title: "Fashion_Women_02",
    url: "/img/Woods_0151_FinTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 372,
    title: "Fashion_Women_03",
    url: "/img/Woods_0013_FinTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 373,
    title: "Fashion_Women_04",
    url: "/img/PandP_0048_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 374,
    title: "Fashion_Women_05",
    url: "/img/PandP_0246_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 375,
    title: "Fashion_Women_06",
    url: "/img/PandP_0292_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 376,
    title: "Fashion_Women_07",
    url: "/img/HushMag01_0150_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 394,
    title: "Fashion_Women_22",
    url: "/img/Liq_0406_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 392,
    title: "Fashion_Women_20",
    url: "/img/Liq_0278_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 393,
    title: "Fashion_Women_21",
    url: "/img/Liq_0313_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 377,
    title: "Fashion_Women_08",
    url: "/img/Hush_Pool_304_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 378,
    title: "Fashion_Women_09",
    url: "/img/Hush_Pool_415_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 379,
    title: "Fashion_Women_10",
    url: "/img/Hush_Pool_485_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 380,
    title: "Fashion_Women_11",
    url: "/img/Hush_Pool_407_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 381,
    title: "Fashion_Women_12",
    url: "/img/Hush_Pool_205_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 382,
    title: "Fashion_Women_10",
    url: "/img/Hush_Pool_221_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 383,
    title: "Fashion_Women_11",
    url: "/img/Theate_0345_Web.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 400,
    title: "Fashion_Women_28",
    url: "/img/MeMag_126_700WebTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 401,
    title: "Fashion_Women_29",
    url: "/img/MeMag_174_WebTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 384,
    title: "Fashion_Women_12",
    url: "/img/Hush_Pool_435_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 385,
    title: "Fashion_Women_13",
    url: "/img/FilmNOIR_117_FinTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 386,
    title: "Fashion_Women_14",
    url: "/img/FilmNoir2_Filim_Fin_WebTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 387,
    title: "Fashion_Women_15",
    url: "/img/FilmNoir3_Film_Fin_WebTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 389,
    title: "Fashion_Women_17",
    url: "/img/LilBD_060_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 390,
    title: "Fashion_Women_18",
    url: "/img/LilBD_163_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 391,
    title: "Fashion_Women_19",
    url: "/img/LilBD_190_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 395,
    title: "Fashion_Women_23",
    url: "/img/Theate_0108_Web.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 396,
    title: "Fashion_Women_24",
    url: "/img/Theate_0394_WebTag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 397,
    title: "Fashion_Women_25",
    url: "/img/Bri_026_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 398,
    title: "Fashion_Women_26",
    url: "/img/Bri_471_700tag.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 399,
    title: "Fashion_Women_27",
    url: "/img/FF_0102_Fin.jpg",
    category: ["digital", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 388,
    title: "Fashion_Women_16",
    url: "/img/WoodsFilm01_WebTag.jpg",
    category: ["film", "color", "fashion:women"],
    description: "Women's Fashion",
  },
  {
    id: 410,
    title: "Music_Port_01",
    url: "/img/Obi_Blur_Fin_700tag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 412,
    title: "Music_Port_03",
    url: "/img/Selina_0134_700tag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 43,
    title: "Korveil",
    url: "/img/Korveil.jpg",
    category: ["digital", "color", "music", "studio"],
    description: "Music Portrait",
  },
  {
    id: 427,
    title: "Music_Port_17",
    url: "/img/STFamily_1.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 411,
    title: "Music_Port_02",
    url: "/img/CacheCity.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 41,
    title: "Jaeno",
    url: "/img/Jaeno.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 35,
    title: "Dave The Producer",
    url: "/img/DaveTheProducer.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait.",
  },
  {
    id: 413,
    title: "Music_Port_04",
    url: "/img/Selina_0452_tag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 414,
    title: "Music_Port_05",
    url: "/img/FAN_341_W2WebTag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 415,
    title: "Music_Port_06",
    url: "/img/FAN_0110_W2_WebTag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 416,
    title: "Music_Port_07",
    url: "/img/Korveil_515_700tag.jpg",
    category: ["digital", "color", "studio", "music"],
    description: "Music Portrait",
  },
  {
    id: 417,
    title: "Music_Port_08",
    url: "/img/CherisaFinal_Web.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 418,
    title: "Music_Port_09",
    url: "/img/Hannibal_564_Tag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 419,
    title: "Music_Port_010",
    url: "/img/IgnacioPortrait---WebTag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 420,
    title: "Music_Port_11",
    url: "/img/Jaeno_0091_Webtag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 421,
    title: "Music_Port_12",
    url: "/img/Rayshawn-2863-Webtag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 422,
    title: "Music_Port_13",
    url: "/img/Rayshawn-2898---Webtag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 423,
    title: "Music_Port_14",
    url: "/img/TreZure_2921-WebTag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 424,
    title: "Music_Port_15",
    url: "/img/Xodus_0224_Tag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 425,
    title: "Music_Port_16",
    url: "/img/Xodus_0333_Fin-Tag.jpg",
    category: ["digital", "color", "music"],
    description: "Music Portrait",
  },
  {
    id: 426,
    title: "Fashion_Men",
    url: "/img/Devand_3.jpg",
    category: ["digital", "color", "fashion:men"],
    description: "Men's Fashion",
  },
  {
    id: 54,
    title: "Plastic Boots",
    url: "/img/PlasticBoots.jpg",
    category: ["digital", "color", "music"],
    description: "This is the description.",
  },
  {
    id: 428,
    title: "Retouch_01",
    url: "/img/Quincy-Touch Sample.jpg",
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample",
  },
  {
    id: 429,
    title: "Retouch_02",
    url: "/img/MeMag_126_TouchSamp.jpg",
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample",
  },
  {
    id: 430,
    title: "Retouch_03",
    url: "/img/LilBD_060_TouchSamp.jpg",
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample",
  },
  {
    id: 431,
    title: "Retouch_04",
    url: "/img/Key_215_TouchSamp.jpg",
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample",
  },
  {
    id: 432,
    title: "Retouch_05",
    url: "/img/Caya_095_TouchSample.jpg",
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample",
  },
  {
    id: 433,
    title: "Retouch_06",
    url: "/img/Bri_026_TouchSamp.jpg",
    category: ["digital", "color", "retouching"],
    description: "Retouching Sample",
  },
];

export default photoCollection;
